# Generated by Django 2.1.4 on 2023-10-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
