# Generated by Django 4.2 on 2023-04-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.TextField(max_length=255)),
                ('key_data', models.BinaryField()),
            ],
        ),
    ]
