# Generated by Django 4.2 on 2023-04-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keygen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publickey',
            name='user_id',
            field=models.TextField(default='', max_length=255),
        ),
    ]
