# Generated by Django 2.1.4 on 2023-10-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keygen', '0003_publickey_cname_publickey_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publickey',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
